"""
tax_data.py — Country-specific tax data for freelancers.
Each entry includes:
  - rate: estimated self-employment / income tax rate (used as default)
  - type: name of the tax system
  - vat: standard VAT/GST rate (if applicable)
  - currency: local currency
  - notes: key filing info
  - faq: list of (question, answer) tuples
  - quarters: local quarter names / filing periods
"""

COUNTRIES = {
    "MU": {
        "name": "Mauritius",
        "currency": "MUR",
        "rate": 15.0,
        "type": "Income Tax (PAYE / Self-Employed)",
        "vat": 15.0,
        "vat_name": "VAT",
        "authority": "Mauritius Revenue Authority (MRA)",
        "authority_url": "https://www.mra.mu",
        "filing_freq": "Annual (+ quarterly APS for income >Rs 2M)",
        "notes": "Flat 15% income tax rate. VAT registration mandatory above Rs 6M turnover. Solidarity Levy applies above Rs 3M.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("What income tax rate applies to freelancers in Mauritius?",
             "Mauritius uses a flat 15% income tax rate for individuals. As a freelancer, your net income (revenue minus allowable expenses) is taxed at 15%. There is no progressive bracket — everyone pays the same rate."),
            ("Do I need to register for VAT in Mauritius?",
             "VAT registration is mandatory if your annual turnover exceeds Rs 6 million. The standard VAT rate is 15%. Below this threshold, registration is optional but you may choose to register voluntarily."),
            ("What is the Advance Payment System (APS)?",
             "If your annual income exceeds Rs 2 million, you must make quarterly advance tax payments to the MRA under the APS scheme. Payments are due in September, December, and March based on estimated annual income."),
            ("What expenses can freelancers deduct in Mauritius?",
             "Allowable deductions include: home office costs (proportion of rent/mortgage), equipment and software, professional subscriptions, training and education, internet and phone (business portion), and travel for business purposes."),
            ("Is there a Solidarity Levy?",
             "Yes. A Solidarity Levy of 25% applies on income exceeding Rs 3 million per year, calculated only on the portion above the Rs 3M threshold. This is in addition to the standard 15% income tax."),
            ("When is the annual tax return due?",
             "The annual income tax return (IT Form) must be filed by 30 September for the preceding tax year (July–June). Late filing attracts penalties of Rs 2,000 per month."),
        ],
    },
    "US": {
        "name": "United States",
        "currency": "USD",
        "rate": 25.0,
        "type": "Federal Income Tax + Self-Employment Tax",
        "vat": 0.0,
        "vat_name": "Sales Tax (state-level)",
        "authority": "Internal Revenue Service (IRS)",
        "authority_url": "https://www.irs.gov",
        "filing_freq": "Quarterly estimated taxes (Apr 15, Jun 15, Sep 15, Jan 15)",
        "notes": "Self-employment tax is 15.3% (SS + Medicare) on top of income tax. Half of SE tax is deductible. Quarterly payments required if you expect to owe >$1,000.",
        "quarters": {1: "Jan–Mar (due Apr 15)", 2: "Apr–May (due Jun 15)", 3: "Jun–Aug (due Sep 15)", 4: "Sep–Dec (due Jan 15)"},
        "faq": [
            ("What taxes does a US freelancer pay?",
             "Freelancers pay: (1) Self-Employment Tax of 15.3% on net earnings up to $168,600 (2024), covering Social Security and Medicare; (2) Federal Income Tax at your bracket rate (10%–37%); and (3) State income tax (varies by state, 0%–13.3%)."),
            ("How do quarterly estimated taxes work?",
             "If you expect to owe more than $1,000 in taxes for the year, you must pay quarterly estimated taxes using Form 1040-ES. Due dates are April 15, June 15, September 15, and January 15. Underpayment results in an IRS penalty."),
            ("Can I deduct the self-employment tax?",
             "Yes — you can deduct 50% of your self-employment tax from your gross income when calculating your adjusted gross income (AGI). This effectively reduces your federal income tax burden."),
            ("What is the QBI deduction for freelancers?",
             "The Qualified Business Income (QBI) deduction allows eligible self-employed individuals to deduct up to 20% of their qualified business income, significantly reducing taxable income. Most freelancers qualify unless in a Specified Service Trade or Business above income thresholds."),
            ("What business expenses are deductible?",
             "Deductible expenses include: home office (Form 8829), health insurance premiums, retirement contributions (SEP-IRA, Solo 401k), equipment and software, professional development, business travel, and half of self-employment tax."),
            ("What is a good tax set-aside percentage?",
             "A commonly recommended rule of thumb is to set aside 25–30% of every payment received. This covers federal self-employment tax (15.3%), federal income tax (~10–22% depending on bracket), and a buffer for state taxes."),
        ],
    },
    "GB": {
        "name": "United Kingdom",
        "currency": "GBP",
        "rate": 20.0,
        "type": "Income Tax + National Insurance",
        "vat": 20.0,
        "vat_name": "VAT",
        "authority": "HM Revenue & Customs (HMRC)",
        "authority_url": "https://www.gov.uk/government/organisations/hm-revenue-customs",
        "filing_freq": "Annual Self Assessment (31 Jan deadline)",
        "notes": "Class 4 NI: 9% on profits £12,570–£50,270, 2% above. Class 2 NI: £3.45/week. VAT registration threshold: £90,000 turnover.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("What taxes does a UK freelancer pay?",
             "UK freelancers pay: (1) Income Tax — 0% up to £12,570 (Personal Allowance), 20% basic rate (£12,570–£50,270), 40% higher rate (£50,270–£125,140); (2) Class 4 National Insurance — 9% on profits £12,570–£50,270, 2% above; (3) Class 2 NI — £3.45/week if profits exceed £12,570."),
            ("When is the Self Assessment deadline?",
             "The Self Assessment tax return must be filed online by 31 January following the tax year end (5 April). Payment of any tax owed is also due 31 January. A payment on account (advance payment) is required if your tax bill exceeds £1,000."),
            ("Do I need to register for VAT?",
             "VAT registration is mandatory when your taxable turnover exceeds £90,000 in any 12-month rolling period (2024/25 threshold). The standard VAT rate is 20%. Below the threshold, registration is optional — the Flat Rate Scheme may benefit small businesses."),
            ("What expenses can I deduct?",
             "HMRC allows deductions for expenses 'wholly and exclusively' for business: home office (£6/week simplified or actual costs), equipment, software subscriptions, professional fees, travel, and pension contributions. Capital allowances apply for larger equipment purchases."),
            ("What is a payment on account?",
             "If your Self Assessment tax bill exceeds £1,000, HMRC requires advance payments: 50% by 31 January and 50% by 31 July. These are estimates based on the prior year's tax bill and offset against your next return."),
            ("How should I structure my freelance business — sole trader or limited company?",
             "As a sole trader you pay income tax + NI on all profits. As a limited company (Ltd), you can pay yourself a salary (£12,570, tax-free) plus dividends (taxed at lower rates: 8.75% basic, 33.75% higher). Ltd companies become tax-efficient above ~£30,000 profit, but have higher admin costs."),
        ],
    },
    "FR": {
        "name": "France",
        "currency": "EUR",
        "rate": 22.0,
        "type": "Impôt sur le Revenu + Cotisations Sociales",
        "vat": 20.0,
        "vat_name": "TVA",
        "authority": "Direction Générale des Finances Publiques (DGFiP)",
        "authority_url": "https://www.impots.gouv.fr",
        "filing_freq": "Annual (May deadline) + quarterly/monthly social charges",
        "notes": "Auto-entrepreneur regime: flat social charges ~22% on revenue. Micro-enterprise threshold: €77,700 (services). Above threshold: régime réel.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("What is the auto-entrepreneur regime?",
             "The auto-entrepreneur (micro-entrepreneur) regime is the simplest structure for French freelancers. You pay a flat rate of social charges on your revenue — approximately 22% for service activities — with no deductions for expenses. Income tax is calculated separately on your net income after an automatic 34% abatement for services."),
            ("What are the turnover limits for micro-enterprise?",
             "For service providers (prestations de services), the annual turnover limit is €77,700 (2024). Exceeding this for two consecutive years moves you to the régime réel, where actual expenses are deducted but accounting becomes more complex."),
            ("How is TVA handled for auto-entrepreneurs?",
             "Auto-entrepreneurs benefit from franchise en base de TVA — you do not charge or collect TVA as long as you stay below €36,800 (services, 2024). Once you exceed this threshold, you must register for TVA at 20% standard rate."),
            ("When and how do I pay social charges?",
             "Social charges (cotisations sociales) are paid monthly or quarterly to URSSAF, based on your declared revenue for that period. The rate for services is approximately 22%. Declarations are made online via autoentrepreneur.urssaf.fr."),
            ("What income tax applies on top of social charges?",
             "Income tax (impôt sur le revenu) uses progressive brackets: 0% up to €11,294, 11% up to €28,797, 30% up to €82,341, 41% up to €177,106, 45% above. Freelancers can opt for the versement libératoire — a flat rate paid monthly alongside social charges (2.2% for services) instead of the standard progressive tax."),
            ("What records must I keep?",
             "Auto-entrepreneurs must keep a daily revenue register (livre des recettes) and a purchase register. Invoices must be numbered sequentially and include your SIRET number, customer details, description of service, date, and amount excluding/including TVA (if applicable)."),
        ],
    },
    "DE": {
        "name": "Germany",
        "currency": "EUR",
        "rate": 25.0,
        "type": "Einkommensteuer + Sozialversicherung",
        "vat": 19.0,
        "vat_name": "Umsatzsteuer (USt)",
        "authority": "Bundeszentralamt für Steuern / Finanzamt",
        "authority_url": "https://www.bzst.de",
        "filing_freq": "Annual Steuererklärung (Jul 31, or Oct 31 with tax advisor)",
        "notes": "Kleinunternehmerregelung: no VAT if turnover <€22,000/year. Solidarity surcharge (Soli) effectively abolished for most. Church tax may apply.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("What is the Kleinunternehmerregelung?",
             "The Kleinunternehmer (small business) rule exempts freelancers from charging Umsatzsteuer (VAT) if their prior year revenue was below €22,000 and current year is expected below €50,000. Your invoices must state 'Gemäß §19 UStG wird keine Umsatzsteuer berechnet.' This simplifies accounting but means you cannot reclaim input VAT."),
            ("What income tax rates apply to freelancers in Germany?",
             "Germany uses progressive income tax: 0% up to €11,604 (Grundfreibetrag 2024), 14–42% for €11,604–€277,826, 45% above (Reichensteuer). The solidarity surcharge (Solidaritätszuschlag) was largely abolished from 2021 and now only applies on very high incomes."),
            ("Do I pay health insurance as a freelancer?",
             "Yes. Freelancers (Freiberufler/Selbstständige) must arrange their own health insurance. Statutory health insurance (GKV) costs approximately 14.6% + supplemental contribution of ~1.6% of income, with a cap. Private health insurance (PKV) is an alternative that may be cheaper for healthy, younger freelancers with higher incomes."),
            ("What is the Vorauszahlung (advance tax payment)?",
             "The Finanzamt may require quarterly advance payments (Einkommensteuer-Vorauszahlung) on 10 March, 10 June, 10 September, and 10 December, based on your prior year's tax liability. These are adjusted annually through your Steuererklärung."),
            ("What expenses are deductible as a Freiberufler?",
             "Deductible Betriebsausgaben include: home office (Arbeitszimmer — strict rules apply, must be separate room used exclusively for work), equipment, software, professional memberships, travel, phone/internet (business portion), education, and pension contributions (up to limits)."),
            ("What is the difference between Freiberufler and Gewerbetreibender?",
             "Freiberufler (liberal professions: designers, writers, consultants, IT professionals) are exempt from Gewerbesteuer (trade tax) and have simpler registration. Gewerbetreibender (tradespeople) must register at the Gewerbeamt and pay Gewerbesteuer on profits above €24,500. Classification determines your tax obligations significantly."),
        ],
    },
    "AU": {
        "name": "Australia",
        "currency": "AUD",
        "rate": 27.5,
        "type": "Income Tax + Medicare Levy",
        "vat": 10.0,
        "vat_name": "GST",
        "authority": "Australian Taxation Office (ATO)",
        "authority_url": "https://www.ato.gov.au",
        "filing_freq": "Annual (Oct 31 self-lodgement, or May 15 via tax agent) + quarterly BAS",
        "notes": "GST registration required at $75,000 turnover. Quarterly BAS lodgement. PAYG instalments for income tax. Medicare Levy: 2% of taxable income.",
        "quarters": {1: "Jul–Sep (Q1 ATO)", 2: "Oct–Dec (Q2)", 3: "Jan–Mar (Q3)", 4: "Apr–Jun (Q4)"},
        "faq": [
            ("What income tax rates apply to Australian freelancers?",
             "Australia uses progressive rates for 2023–24: 0% up to $18,200 (tax-free threshold), 19% for $18,201–$45,000, 32.5% for $45,001–$120,000, 37% for $120,001–$180,000, 45% above $180,000. Plus 2% Medicare Levy on all taxable income (low-income earners may be exempt)."),
            ("When must I register for GST?",
             "GST registration is mandatory when your turnover reaches or is expected to reach $75,000 in any 12-month period. Once registered, you charge 10% GST on taxable supplies, lodge quarterly Business Activity Statements (BAS), and can claim GST credits on business purchases."),
            ("What are PAYG instalments?",
             "Pay As You Go (PAYG) instalments are quarterly advance income tax payments, typically required once your notional tax exceeds $500. The ATO calculates an instalment rate based on your prior year income. Instalments are due with each quarterly BAS."),
            ("What deductions can Australian freelancers claim?",
             "Deductible work-related expenses include: home office running costs (67 cents/hour fixed rate or actual costs method), equipment depreciation, professional subscriptions, work-related travel, phone and internet (business percentage), professional development, and income protection insurance premiums."),
            ("What is the Low Income Tax Offset (LITO)?",
             "The LITO reduces tax for freelancers earning under $66,667. The maximum offset is $700 for incomes up to $37,500, phasing out to $0 at $66,667. This effectively means no tax is payable on income below approximately $21,887 when combined with the tax-free threshold."),
            ("Do I need to pay superannuation contributions?",
             "As a self-employed freelancer, you are not legally required to pay yourself superannuation, but you can make voluntary concessional (tax-deductible) contributions up to $27,500 per year (2023–24). Super contributions are taxed at only 15%, making them an effective tax minimisation strategy for higher-income freelancers."),
        ],
    },
    "CA": {
        "name": "Canada",
        "currency": "CAD",
        "rate": 26.0,
        "type": "Federal + Provincial Income Tax + CPP",
        "vat": 5.0,
        "vat_name": "GST/HST",
        "authority": "Canada Revenue Agency (CRA)",
        "authority_url": "https://www.canada.ca/en/revenue-agency.html",
        "filing_freq": "Annual (Apr 30, self-employed Jun 15) + quarterly GST/HST",
        "notes": "CPP contributions ~11.4% on net self-employment income (up to $68,500). GST/HST registration required at $30,000 annual revenue.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("What taxes does a Canadian freelancer pay?",
             "Canadian freelancers pay: (1) Federal income tax (15%–33% progressive brackets); (2) Provincial/territorial income tax (varies by province, ~5%–21%); (3) Canada Pension Plan (CPP) contributions — both employee and employer portions, totalling approximately 11.4% on net self-employment income up to $68,500 for 2024."),
            ("When must I register for GST/HST?",
             "GST/HST registration is mandatory once your total revenues from taxable supplies exceed $30,000 in any single calendar quarter or in four consecutive calendar quarters. Voluntary registration before this threshold allows you to claim input tax credits on business expenses."),
            ("What is the difference between GST, HST, and QST?",
             "GST (5%) applies in all provinces. HST (13%–15%) is a harmonized tax combining federal GST and provincial tax, applying in Ontario, Nova Scotia, New Brunswick, Newfoundland, and PEI. Quebec has its own system: GST (5%) + QST (9.975%). As a freelancer, you charge the rate applicable in your client's province."),
            ("What business expenses are deductible in Canada?",
             "The CRA allows deductions for: business use of home (calculated on square footage), vehicle expenses (business kilometres log required), advertising, professional fees, equipment (via Capital Cost Allowance), business insurance, and professional development. Meals and entertainment are 50% deductible."),
            ("Can I income split with my spouse?",
             "Income splitting with a spouse or family member who works in your business is allowed if they perform genuine services and are paid a reasonable market rate. The CRA scrutinises this closely — maintain proper records and pay amounts consistent with what you'd pay a third party."),
            ("What is a good tax savings strategy for Canadian freelancers?",
             "Key strategies: (1) Maximize RRSP contributions (up to 18% of prior year income, deducted from taxable income); (2) TFSA for tax-free growth; (3) Deduct all legitimate business expenses; (4) Incorporate once income exceeds ~$80,000 (small business tax rate of 9% federally vs personal rates)."),
        ],
    },
    "IN": {
        "name": "India",
        "currency": "INR",
        "rate": 30.0,
        "type": "Income Tax (Presumptive / Regular) + GST",
        "vat": 18.0,
        "vat_name": "GST",
        "authority": "Income Tax Department / GSTN",
        "authority_url": "https://www.incometax.gov.in",
        "filing_freq": "Annual ITR (Jul 31) + GST monthly/quarterly returns",
        "notes": "Section 44ADA: presumptive taxation at 50% of gross receipts for professionals (limit Rs 75L). GST registration required at Rs 20L turnover (Rs 10L in special states).",
        "quarters": {1: "Apr–Jun", 2: "Jul–Sep", 3: "Oct–Dec", 4: "Jan–Mar"},
        "faq": [
            ("What is Section 44ADA and how does it help freelancers?",
             "Section 44ADA is the presumptive taxation scheme for professionals (including designers, writers, IT consultants, lawyers, doctors). If your gross receipts are under Rs 75 lakh, you can declare 50% of receipts as net income and pay tax on that — without maintaining detailed books of accounts. This significantly simplifies compliance."),
            ("What income tax slabs apply for freelancers in India?",
             "Under the New Tax Regime (default from AY 2024–25): 0% up to Rs 3 lakh, 5% Rs 3–7L, 10% Rs 7–10L, 15% Rs 10–12L, 20% Rs 12–15L, 30% above Rs 15L. A standard deduction of Rs 75,000 applies. Under the Old Regime, you keep deductions (80C, HRA, etc.) but higher slabs apply."),
            ("When must I register for GST as a freelancer?",
             "GST registration is mandatory when annual turnover exceeds Rs 20 lakh (Rs 10 lakh in special category states). For digital/online services exported to foreign clients, GST registration may be required from the first rupee. Exports are zero-rated (0% GST) but registration enables LUT filing to avoid collecting GST."),
            ("Do I need to pay advance tax?",
             "Yes. If your total tax liability exceeds Rs 10,000 in a year, you must pay advance tax in four instalments: 15% by June 15, 45% by September 15, 75% by December 15, and 100% by March 15. Under Section 44ADA, advance tax is due as a single payment by March 15."),
            ("What TDS applies to freelancer payments?",
             "Clients must deduct TDS under Section 194J at 10% (professional fees) or Section 194C at 1-2% (contractor fees) when payments exceed specified thresholds. You can claim this TDS credit when filing your ITR. If your income is below the taxable threshold, file Form 15G/15H to avoid TDS deduction."),
            ("How should I invoice foreign clients from India?",
             "Invoices to foreign clients should be in USD/EUR with a conversion note. Export of services is zero-rated under GST — file a Letter of Undertaking (LUT) annually to export without paying IGST. Receive payments through RBI-authorised channels (bank wire, PayPal Business). Report foreign income in your ITR under 'income from profession'."),
        ],
    },
    "ZA": {
        "name": "South Africa",
        "currency": "ZAR",
        "rate": 26.0,
        "type": "Income Tax + Provisional Tax",
        "vat": 15.0,
        "vat_name": "VAT",
        "authority": "South African Revenue Service (SARS)",
        "authority_url": "https://www.sars.gov.za",
        "filing_freq": "Annual ITR12 + bi-annual provisional tax (Aug 31, Feb 28)",
        "notes": "Provisional tax: 2 payments per year. VAT registration mandatory at R1 million annual turnover. Small business corporation (SBC) rates available for PTY.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("How does provisional tax work for South African freelancers?",
             "Freelancers are classified as provisional taxpayers. You make two advance tax payments per year: the first by 31 August (for the first 6 months of the tax year, March–August) and the second by 28 February (for the full year). A voluntary third payment can be made by 30 September if additional tax is owed. Interest and penalties apply for underpayment."),
            ("What are the income tax rates in South Africa?",
             "For the 2024/25 tax year: 18% on taxable income up to R237,100; 26% for R237,101–R370,500; 31% for R370,501–R512,800; 36% for R512,801–R673,000; 39% for R673,001–R857,900; 41% for R857,901–R1,817,000; 45% above R1,817,000. The primary rebate of R17,235 effectively creates a tax-free threshold of ~R95,750."),
            ("When must I register for VAT in South Africa?",
             "VAT registration is compulsory when your taxable supplies exceed R1 million in any 12-month period (or expected to). Voluntary registration is possible at R50,000. The standard VAT rate is 15%. Exports of services to non-residents may be zero-rated."),
            ("What business expenses are deductible?",
             "SARS allows deductions under Section 11 for expenses 'actually incurred in the production of income': home office (apportioned — SARS applies a strict test that home office must be used regularly and exclusively for trade); equipment, software, professional fees, travel (with logbook), professional subscriptions, and retirement annuity contributions (up to 27.5% of income, max R350,000)."),
            ("What is the Medical Tax Credit?",
             "Even as a freelancer, you are entitled to a monthly Medical Scheme Fees Tax Credit (MTC) of R364 for the primary member and the first dependant, and R246 for each additional dependant. This directly reduces your tax liability and is claimed in your ITR12."),
            ("Do I need an accountant to file in South Africa?",
             "While not legally required, many freelancers use an accountant or tax practitioner for their ITR12. SARS eFiling allows self-filing. Key deadlines: 31 October for non-provisional paper filers, 20 January for eFilers, and 29 February for provisional taxpayers filing via eFiling."),
        ],
    },
    "OTHER": {
        "name": "Other / Manual",
        "currency": "USD",
        "rate": 25.0,
        "type": "Custom (manually defined)",
        "vat": 0.0,
        "vat_name": "Tax",
        "authority": "Your local tax authority",
        "authority_url": "",
        "filing_freq": "Consult your local tax authority",
        "notes": "You have chosen to set your tax rate manually. Consult a local accountant for accurate rates.",
        "quarters": {1: "Jan–Mar", 2: "Apr–Jun", 3: "Jul–Sep", 4: "Oct–Dec"},
        "faq": [
            ("How is the estimated tax calculated?",
             "The estimated tax is calculated as your chosen tax rate applied to your net income (total income minus total expenses). This is a rough estimate — your actual tax liability will depend on allowances, deductions, and your country's specific rules."),
            ("Should I consult a tax professional?",
             "Yes. Tax laws vary significantly by country, jurisdiction, and individual circumstances. This tool provides an estimate to help you plan, but a qualified accountant or tax professional in your country will give you accurate, legally compliant advice."),
            ("How often should I set aside money for tax?",
             "A good practice is to set aside your estimated tax percentage from every payment you receive, immediately into a separate savings account. This way the money is always ready when your tax bill arrives."),
            ("What counts as a deductible business expense?",
             "Generally: equipment and software used for your work, professional subscriptions, home office costs (proportional), business travel, professional development, and business insurance. Keep all receipts. Your local tax authority sets the specific rules."),
        ],
    },
}

def get_country(code: str) -> dict:
    return COUNTRIES.get(code.upper(), COUNTRIES["OTHER"])

def country_choices() -> list:
    """Returns list of (code, name) for select dropdown."""
    result = [(k, v["name"]) for k, v in COUNTRIES.items() if k != "OTHER"]
    result.sort(key=lambda x: x[1])
    result.append(("OTHER", "Other / Manual"))
    return result
